version: 2.1
orbs:
  coverage-reporter: codacy/coverage-reporter@12.1.0
jobs:
  build:
    docker:
      - image: circleci/node:12
      - image: cypress/base:14.16.0
        environment:
          ## this enables colors in the output
          TERM: xterm

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build App
          command: yarn build

      - run:
          name: Run Lint
          command: yarn eslint

      - run:
          name: Run test
          command: yarn test:ci --coverage



      - store_test_results:
          path: coverage

      - store_artifacts:
          path: coverage

      - coverage-reporter/send_report:
          coverage-reports: 'coverage/clover.xml, coverage/lcov.info'
          project-token: e269adafdb06498187ba1cdc6279ed73
          
      - run:
          name: Running E2E tests with cypress reporter
          command: yarn e2e:headless
      - store_test_results:
          path: cypress/results

      - store_artifacts:
          path: cypress/videos

      - store_artifacts:
          path: cypress/screenshots

  deploy:
    machine:
      image: ubuntu-1604:202007-01

    steps:
      - run:
          command: curl -X POST -d {} ${deploy_endpoint}
  

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build