version: 2.1
orbs:
  coverage-reporter: codacy/coverage-reporter@12.1.0
  cypress: cypress-io/cypress@1.29.0
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Lint
          command: yarn eslint

      - run:
          name: Run test
          command: yarn test:ci --coverage

      - store_test_results:
          path: 'coverage/clover.xml, coverage/lcov.info'

      - store_artifacts:
          path: coverage

      - coverage-reporter/send_report:
          coverage-reports: 'coverage/clover.xml, coverage/lcov.info'
          project-token: e269adafdb06498187ba1cdc6279ed73

  deploy:
    machine:
      image: ubuntu-1604:202007-01

    steps:
      - run:
          name: Netlify Deploy
          command: curl -X POST -d {} ${deploy_endpoint}

      - run:
          name: Vercel Deploy
          command: curl -X POST -d {} ${deploy_endpoint}
          

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - cypress/install:
          install-command: yarn install --ignore-engines --frozen-lockfile
          requires:
            - build

      - cypress/run:
          install-command: yarn install --ignore-engines --frozen-lockfile
          build: yarn build
          requires:
            - cypress/install
          store_artifacts: true
          record: true
          post-steps:
            - store_test_results:
                path: cypress/results
          command: yarn e2e:headless

      - deploy:
          requires:
            - build
            - cypress/run